version: "3.9"
services:
  ytbridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytbridge
    dns:
#      - 1.1.1.1
      - 172.17.0.1
    environment:
      - BACKEND_PROVIDER=${BACKEND_PROVIDER:-invidious}
      - BACKEND_BASE=${BACKEND_BASE:-https://yewtu.be}
      - YTDLP_MODE=${YTDLP_MODE:-local}
      # Point to your mounted host binary (see volume below)
      - YTDLP_CMD=${YTDLP_CMD:-/usr/local/bin/yt-dlp_linux}
      # Use your original cookies path if you used it before, or leave empty
      - YTDLP_COOKIES=${YTDLP_COOKIES:-/app/cookies.txt}
      - SPONSORBLOCK=${SPONSORBLOCK:-true}
      - PORT=${PORT:-8080}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_TTL=${REDIS_TTL:-43200}
      - FFMPEG_CMD=${FFMPEG_CMD:-ffmpeg}
      - DATA_DIR=${DATA_DIR:-/data}
    volumes:
      # Code (optional live mount)
      - ./src:/app/src:ro
      # Match your original data dir
      - ./data:/data
      # Mount your cookies exactly where YTDLP_COOKIES points (optional)
#      - ./cookies.txt:/data/cookies.txt:ro
      # Mount your custom yt-dlp host binary exactly where YTDLP_CMD points
      - ~/.yt-dlp/bin/yt-dlp_linux:/usr/local/bin/yt-dlp_linux
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    networks:
      - jellyfin
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ytbridge-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - jellyfin
    restart: unless-stopped
networks:
  jellyfin:
    external: true
