version: "3.9"
services:
  ytbridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytbridge
    dns:
#      - 1.1.1.1
      - 172.17.0.1
    environment:
      - STREAM_MODE=proxy
      - BACKEND_PROVIDER=ytdlp      # ← explicit, not ${...}
      - BACKEND_BASE=               # ← empty to disable invidious
      - YTDLP_MODE=local
      - YTDLP_CMD=/usr/local/bin/yt-dlp_linux
      - YTDLP_COOKIES=/app/cookies.txt
      - PORT=8080
      - REDIS_URL=redis://redis:6379/0
      - REDIS_TTL=43200
      - FFMPEG_CMD=ffmpeg
      - DATA_DIR=/data
    volumes:
      # Code (optional live mount)
      - ./src:/app/src:ro
      # Match your original data dir
      - ./data:/data
      # Mount your cookies exactly where YTDLP_COOKIES points (optional)
#      - ./cookies.txt:/data/cookies.txt:ro
      # Mount your custom yt-dlp host binary exactly where YTDLP_CMD points
      - ~/.yt-dlp/bin/yt-dlp_linux:/usr/local/bin/yt-dlp_linux
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    networks:
      - jellyfin
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ytbridge-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - jellyfin
    restart: unless-stopped
networks:
  jellyfin:
    external: true
