# docker-compose.yaml
version: "3.9"
services:
  ytbridge:
    image: python:3.12-slim
    container_name: ytbridge
    working_dir: /app
    command: ["bash","-lc","pip install --no-cache-dir fastapi uvicorn httpx yt-dlp redis python-multipart && uvicorn yt_bridge:app --host 0.0.0.0 --port ${PORT:-8080}"]
    environment:
      - BACKEND_PROVIDER=${BACKEND_PROVIDER:-invidious}
      - BACKEND_BASE=${BACKEND_BASE:-https://yewtu.be}
      - YTDLP_MODE=${YTDLP_MODE:-local}
      - YTDLP_CMD=${YTDLP_CMD:-/usr/local/bin/yt-dlp}
      - YTDLP_COOKIES=${YTDLP_COOKIES:-}
      - SPONSORBLOCK=${SPONSORBLOCK:-true}
      - PORT=${PORT:-8080}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_TTL=${REDIS_TTL:-43200}
    volumes:
      - ./yt_bridge.py:/app/yt_bridge.py:ro          # renamed app
      - ./cookies.txt:/app/cookies.txt            # optional
      - ~/.yt-dlp/bin/yt-dlp_linux:/usr/local/bin/yt-dlp_linux:ro
      - ./data:/data
#      - /usr/local/bin/yt-dlp:/usr/local/bin/yt-dlp:ro  # host binary mounted in
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ytbridge-redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
