version: "3.9"
services:
  ytbridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytbridge
    environment:
      - BACKEND_PROVIDER=${BACKEND_PROVIDER:-invidious}
      - BACKEND_BASE=${BACKEND_BASE:-https://yewtu.be}
      - YTDLP_MODE=${YTDLP_MODE:-local}
      - YTDLP_CMD=${YTDLP_CMD:-/usr/local/bin/yt-dlp}
      - YTDLP_REMOTE_URL=${YTDLP_REMOTE_URL:-}
      - YTDLP_COOKIES=${YTDLP_COOKIES:-}
      - SPONSORBLOCK=${SPONSORBLOCK:-true}
      - PORT=${PORT:-8080}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_TTL=${REDIS_TTL:-43200}
      - FFMPEG_CMD=${FFMPEG_CMD:-ffmpeg}
      - DATA_DIR=${DATA_DIR:-/app/priv/data}
    volumes:
      # Optional: mount local src for live dev (comment for production)
      - ./src:/app/src:ro
      # Persist cookies/subscriptions/favorites
      - ./priv:/app/priv
      # Optional: provide a custom yt-dlp binary
      # - ~/.yt-dlp/bin/yt-dlp_linux:/usr/local/bin/yt-dlp:ro
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ytbridge-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
