
version: "3.9"
services:
  ytbridge:
    image: python:3.12-slim
    container_name: ytbridge
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir fastapi uvicorn httpx yt-dlp redis && uvicorn app:app --host 0.0.0.0 --port ${PORT:-8080}"
    environment:
      - BACKEND_PROVIDER=${BACKEND_PROVIDER:-invidious}
      - BACKEND_BASE=${BACKEND_BASE:-https://yewtu.be}
      - YTDLP_COOKIES=${YTDLP_COOKIES:-}
      - SPONSORBLOCK=${SPONSORBLOCK:-true}
      - PORT=${PORT:-8080}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_TTL=${REDIS_TTL:-43200}
    volumes:
      - ./app.py:/app/app.py:ro
      - ./cookies.txt:/app/cookies.txt:ro
    ports:
      - "127.0.0.1:${PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ytbridge-redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
